### ISSUE TITLE
"Canned response" or similar feature to re-use solutions

### ISSUE THREAD

**Issue by shwina** [aci-ref/facilitation_best_practices#15]
Suggestion: add a mention about "canned responses" (http://www.wikihow.com/Use-Canned-Responses-in-Gmail) as a way to re-use common replies to e-mail questions/tickets? Happy to do the writing.

**Comment by lmichael107** [comment]
Go for it! I also frequently will copy and paste a similar response (then tweak) from a different but researcher inquiry.

**Comment by lmichael107** [comment]
Checking in. Have you pursued this update yet?
-Lauren

**Comment by shwina** [comment]
Pull request created and merged #20. Closing.
