### ISSUE TITLE
Campus Champion language

### ISSUE THREAD

**Issue by kellyrowland** [aci-ref/facilitation_best_practices#25]
Hi,

On the "Enhancing ACI Knowledge" page, "Campus champions" is listed as a professional network.

I personally understand this to refer to the (current) XSEDE program, but a Google search for "campus champions" offers [this](https://www.schooldude.com/community/engage/campus-champions/become-a-campus-champion) in the first page of results.

I also understand that the XSEDE Campus Champions program is undergoing some changes at the moment, but it might be useful to specify that this page is indeed referring to the XSEDE program and not the thing linked above (or anything else).

**Comment by ChristinaLK** [comment]
Good point -- we have a longer title + link farther up in the chapter and could just copy that farther down.

**Comment by lmichael107** [comment]
Yes. @scleveland should make the change to "XSEDE Campus Champions" with the proper link, since it's his chapter.

**Comment by scleveland** [comment]
Resolved by commit #28856e3
