### ISSUE TITLE
Punctuation in bulleted lists

### ISSUE THREAD

**Issue by erinshawusc** [aci-ref/facilitation_best_practices#3]
I'm going to edit Engagement, to add/delete full stops and some upper casing with the bulleted lists, for consistency.

**Comment by lmichael107** [comment]
Great! Will you close this issue once you've made the change. You can even reference a pull request by clicking the starred flag in the top right of the "Write" box (below) when you respond to this comment and click "Close issue" on GitHub. The reference will look like this: #3

**Comment by lmichael107** [comment]
Hi Erin,

If you've deemed this issue as 'fixed', please close it and refer to the pull request with the changes.

Lauren
